---
os: linux
dist: xenial
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - "# Update system gems if requested. This is useful to temporarily workaround troubles in the test runner"
  - "# See https://github.com/puppetlabs/pdk-templates/commit/705154d5c437796b821691b707156e1b056d244f for an example of how this was used"
  - "# Ignore exit code of SIGPIPE'd yes to not fail with shell's pipefail set"
  - '[ -z "$RUBYGEMS_VERSION" ] || (yes || true) | gem update --system $RUBYGEMS_VERSION'
  - gem --version
  - bundle -v
script:
  - 'SIMPLECOV=yes bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.7
env:
  global:
    - HONEYCOMB_WRITEKEY="7f3c63a70eecc61d635917de46bea4e6",HONEYCOMB_DATASET="litmus tests"
stages:
  - static
  - spec
  - acceptance
jobs:
  fast_finish: true
  include:
    - before_script:
      - "bundle exec rake 'litmus:provision_list[travis_deb]'"
      - "bundle exec rake 'litmus:install_agent[puppet6]'"
      - "bundle exec rake litmus:install_module"
      env:
        PLATFORMS: travis_deb_puppet6
        BUNDLE_WITH: system_tests
      rvm: 2.5.7
      script: ["travis_wait 45 bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
    - before_script:
      - "bundle exec rake 'litmus:provision_list[travis_ub]'"
      - "bundle exec rake 'litmus:install_agent[puppet6]'"
      - "bundle exec rake litmus:install_module"
      env:
        PLATFORMS: travis_ub_puppet6
        BUNDLE_WITH: system_tests
      rvm: 2.5.7
      script: ["travis_wait 45 bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
    - before_script:
      - "bundle exec rake 'litmus:provision_list[travis_el7]'"
      - "bundle exec rake 'litmus:install_agent[puppet6]'"
      - "bundle exec rake litmus:install_module"
      env:
        PLATFORMS: travis_el7_puppet6
        BUNDLE_WITH: system_tests
      rvm: 2.5.7
      script: ["travis_wait 45 bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
    - before_script:
      - "bundle exec rake 'litmus:provision_list[travis_el8]'"
      - "bundle exec rake 'litmus:install_agent[puppet6]'"
      - "bundle exec rake litmus:install_module"
      env:
        PLATFORMS: travis_el8_puppet6
        BUNDLE_WITH: system_tests
      rvm: 2.5.7
      script: ["travis_wait 45 bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.7
      stage: spec
branches:
  only:
    - main
    - /^v\d/
    - release
notifications:
  email: false
  slack:
    secure: bkgukmfDEw0pA7mx0e8UU4p4GmpWL/s7kC5D/3XyqNilYI5SArkAt5MTnwMn7/GSF0JRspcrt3J9Y69lNseE5dDegArlht6D2c5Ad8o0ibrCN7yuz6XVyiODyYf32+w/lzsaTQJ1E/55HgTKJ9Tzk8sPlLsYcSEt2OGm+hR/2AoaLi6M8WSc5fCmTUI7AgLnT95jbDu5ioJkOILGCet47A24MXKR2jNaQ7KYhiQ8xqXPZ3Zp0N/bZuYjDiYEeRbjHWvALyInQVqCytv9aLW5v7tg4IjhkyYrDf4g5XamU2909uyTgHT+M/nuPsScnyEu5YdSWT9RqoAHhADz+7daFcgVtUIN5K8EEaNmA8b/nXrGnSh2S1MJ/D/lbo176oHiKh/KME0/L7+YfCxnyGMaraUcxVjj9FQzBDRDIiyDqJOVe4v0cpkdEuCgJTgaIJ2NLHVmJzgGYTuIp/xV2/zWEgqNxz977ydsPObU0T0MCqpzaFR7a5zj3hsNlGa25bbehDGUyi7MFi6TVQMRYhldiZXydERCFaBbKfOT5xfNNpu3FZmi7t1Tu2sClZFwKW9OachoDI/NFam6+D/Q2nuuAl+p/L5edeF3ciGTjMr9OGZeLqFS/6fUxfM/GP/3bDBzF8RN6gZW5HQdtJkXq5GbpifKsA9gEL4VbPKqNhEtDss=
